[package]
name = "popola"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = "0.36.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.devola]
path = "./devola"
